interface = "enp0s20f0u3"
scion_folder = "/home/heimdall/Repos/scion-bootstrapper/go/sciond"

[mechanisms]
  [dhcp]
    enable = true
  [dnssd]
    enableSD = false
    enableNAPTR = false
  [mdns]
    enable = false

[log]
  [log.console]
    level = "debug"
